<a href="https://colab.research.google.com/github/imchihchao/aop113b/blob/main/nb03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Series

In [ ]:
import pandas as pd

# 宣告建立一維資料 Series
age = [25, 30, 35, 40, 22, 29, 38, 27, 33, 31]
se = pd.Series(age)

In [ ]:
se

0    25
1    30
2    35
3    40
4    22
5    29
6    38
7    27
8    33
9    31
dtype: int64

In [ ]:
se.values
se.index
se.dtype

dtype('int64')

In [ ]:
# 自訂索引
name = ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack']
age = [25, 30, 35, 40, 22, 29, 38, 27, 33, 31]
seidx = pd.Series(age, index=name)
seidx

Alice      25
Bob        30
Charlie    35
David      40
Eve        22
Frank      29
Grace      38
Helen      27
Ivy        33
Jack       31
dtype: int64

In [ ]:
seidx.index

Index(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen',
       'Ivy', 'Jack'],
      dtype='object')

In [ ]:
se[3]

np.int64(40)

In [ ]:
se.loc[3]

np.int64(40)

In [ ]:
se.iloc[3]

np.int64(40)

In [ ]:
seidx.loc['David']

np.int64(40)

In [ ]:
seidx.iloc[3]

np.int64(40)

## DataFrame

In [ ]:
import pandas as pd

data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 29, 38, 27, 33, 31],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [50000, 60000, 75000, 80000, 45000, 62000, 72000, 58000, 69000, 71000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance']
}
df = pd.DataFrame(data)
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [ ]:
df.values
df.index
df.columns
df.dtypes

ID             int64
Name          object
Age            int64
City          object
Salary         int64
Department    object
dtype: object

In [ ]:
df.values[1]

array([102, 'Bob', 30, 'Los Angeles', 60000, 'HR'], dtype=object)

In [ ]:
df.loc[1]

ID                    102
Name                  Bob
Age                    30
City          Los Angeles
Salary              60000
Department             HR
Name: 1, dtype: object

In [ ]:
df.iloc[1]

ID                    102
Name                  Bob
Age                    30
City          Los Angeles
Salary              60000
Department             HR
Name: 1, dtype: object

In [ ]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7      Helen
8        Ivy
9       Jack
Name: Name, dtype: object

In [ ]:
df[['Name']]

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eve
5    Frank
6    Grace
7    Helen
8      Ivy
9     Jack

## 資料檢索

In [ ]:
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [ ]:
# 取得指定儲存格的值
df.values[2, 1] # [列,欄]
df.loc[2, 'Name']
df.iloc[2, 1]

'Charlie'

In [ ]:
# 指定範圍取值
df.iloc[2:6, 1:4]

      Name  Age          City
2  Charlie   35       Chicago
3    David   40       Houston
4      Eve   22       Phoenix
5    Frank   29  Philadelphia

In [ ]:
# 注意 loc 和 iloc 的取值範圍
df.loc[2:6, 'Name':'Salary']

      Name  Age          City  Salary
2  Charlie   35       Chicago   75000
3    David   40       Houston   80000
4      Eve   22       Phoenix   45000
5    Frank   29  Philadelphia   62000
6    Grace   38   San Antonio   72000

In [ ]:
df.head(3)

    ID     Name  Age         City  Salary Department
0  101    Alice   25     New York   50000         IT
1  102      Bob   30  Los Angeles   60000         HR
2  103  Charlie   35      Chicago   75000    Finance

In [ ]:
dfidx = df.set_index('ID')
dfidx

        Name  Age          City  Salary Department
ID
101    Alice   25      New York   50000         IT
102      Bob   30   Los Angeles   60000         HR
103  Charlie   35       Chicago   75000    Finance
104    David   40       Houston   80000  Marketing
105      Eve   22       Phoenix   45000         IT
106    Frank   29  Philadelphia   62000         HR
107    Grace   38   San Antonio   72000    Finance
108    Helen   27     San Diego   58000  Marketing
109      Ivy   33        Dallas   69000         IT
110     Jack   31      San Jose   71000    Finance

In [ ]:
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [ ]:
dfidx.loc[109]

Name             Ivy
Age               33
City          Dallas
Salary         69000
Department        IT
Name: 109, dtype: object

In [ ]:
condition = (df['Age'] > 30) | (df['Salary'] > 70000)

df[  (df['Age'] > 30) & (df['Salary'] > 70000)  ]

    ID     Name  Age         City  Salary Department
2  103  Charlie   35      Chicago   75000    Finance
3  104    David   40      Houston   80000  Marketing
6  107    Grace   38  San Antonio   72000    Finance
9  110     Jack   31     San Jose   71000    Finance

In [ ]:
df.describe()

              ID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  31.000000  64200.000000
std      3.02765   5.656854  11193.251935
min    101.00000  22.000000  45000.000000
25%    103.25000  27.500000  58500.000000
50%    105.50000  30.500000  65500.000000
75%    107.75000  34.500000  71750.000000
max    110.00000  40.000000  80000.000000

In [ ]:
df['Salary'].mean()

np.float64(64200.0)

In [ ]:
df.count()

ID            10
Name          10
Age           10
City          10
Salary        10
Department    10
dtype: int64

In [ ]:
df['Department'].unique()

array(['IT', 'HR', 'Finance', 'Marketing'], dtype=object)

In [ ]:
df['Department'].value_counts()

Department
IT           3
Finance      3
HR           2
Marketing    2
Name: count, dtype: int64

In [ ]:
df['salary_rank'] = df['Salary'].rank()

In [ ]:
df

    ID     Name  Age          City  Salary Department  salary_rank
0  101    Alice   25      New York   50000         IT          2.0
1  102      Bob   30   Los Angeles   60000         HR          4.0
2  103  Charlie   35       Chicago   75000    Finance          9.0
3  104    David   40       Houston   80000  Marketing         10.0
4  105      Eve   22       Phoenix   45000         IT          1.0
5  106    Frank   29  Philadelphia   62000         HR          5.0
6  107    Grace   38   San Antonio   72000    Finance          8.0
7  108    Helen   27     San Diego   58000  Marketing          3.0
8  109      Ivy   33        Dallas   69000         IT          6.0
9  110     Jack   31      San Jose   71000    Finance          7.0

In [ ]:
df.sort_values(by='Age', ascending=False)

    ID     Name  Age          City  Salary Department  salary_rank
3  104    David   40       Houston   80000  Marketing         10.0
6  107    Grace   38   San Antonio   72000    Finance          8.0
2  103  Charlie   35       Chicago   75000    Finance          9.0
8  109      Ivy   33        Dallas   69000         IT          6.0
9  110     Jack   31      San Jose   71000    Finance          7.0
1  102      Bob   30   Los Angeles   60000         HR          4.0
5  106    Frank   29  Philadelphia   62000         HR          5.0
7  108    Helen   27     San Diego   58000  Marketing          3.0
0  101    Alice   25      New York   50000         IT          2.0
4  105      Eve   22       Phoenix   45000         IT          1.0

In [ ]:
df

    ID     Name  Age          City  Salary Department  salary_rank
0  101    Alice   25      New York   50000         IT          2.0
1  102      Bob   30   Los Angeles   60000         HR          4.0
2  103  Charlie   35       Chicago   75000    Finance          9.0
3  104    David   40       Houston   80000  Marketing         10.0
4  105      Eve   22       Phoenix   45000         IT          1.0
5  106    Frank   29  Philadelphia   62000         HR          5.0
6  107    Grace   38   San Antonio   72000    Finance          8.0
7  108    Helen   27     San Diego   58000  Marketing          3.0
8  109      Ivy   33        Dallas   69000         IT          6.0
9  110     Jack   31      San Jose   71000    Finance          7.0

In [ ]:
df[['ID','Age','Salary']].sum(axis=1)

0    50126
1    60132
2    75138
3    80144
4    45127
5    62135
6    72145
7    58135
8    69142
9    71141
dtype: int64

In [ ]:
grp = df.groupby('Department')

In [ ]:
grp.get_group('IT')

    ID   Name  Age      City  Salary Department  salary_rank
0  101  Alice   25  New York   50000         IT          2.0
4  105    Eve   22   Phoenix   45000         IT          1.0
8  109    Ivy   33    Dallas   69000         IT          6.0

In [ ]:
grp['Salary'].mean()

Department
Finance      72666.666667
HR           61000.000000
IT           54666.666667
Marketing    69000.000000
Name: Salary, dtype: float64

## 資料清理

In [ ]:
import pandas as pd

data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 29, 38, 27, 33, 31],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [50000, 60000, 75000, 80000, 45000, 62000, 72000, 58000, 69000, 71000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance']
}
df = pd.DataFrame(data)
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [ ]:
df['Company'] = 'TechCorp'

In [ ]:
df

    ID     Name  Age          City  Salary Department   Company
0  101    Alice   25      New York   50000         IT  TechCorp
1  102      Bob   30   Los Angeles   60000         HR  TechCorp
2  103  Charlie   35       Chicago   75000    Finance  TechCorp
3  104    David   40       Houston   80000  Marketing  TechCorp
4  105      Eve   22       Phoenix   45000         IT  TechCorp
5  106    Frank   29  Philadelphia   62000         HR  TechCorp
6  107    Grace   38   San Antonio   72000    Finance  TechCorp
7  108    Helen   27     San Diego   58000  Marketing  TechCorp
8  109      Ivy   33        Dallas   69000         IT  TechCorp
9  110     Jack   31      San Jose   71000    Finance  TechCorp

In [ ]:
# 新增「年薪」欄位（假設每年有 12 個月薪資）
df['Annual Salary'] = df['Salary'] * 13.5
df

    ID     Name  Age          City  Salary Department   Company  Annual Salary
0  101    Alice   25      New York   50000         IT  TechCorp       675000.0
1  102      Bob   30   Los Angeles   60000         HR  TechCorp       810000.0
2  103  Charlie   35       Chicago   75000    Finance  TechCorp      1012500.0
3  104    David   40       Houston   80000  Marketing  TechCorp      1080000.0
4  105      Eve   22       Phoenix   45000         IT  TechCorp       607500.0
5  106    Frank   29  Philadelphia   62000         HR  TechCorp       837000.0
6  107    Grace   38   San Antonio   72000    Finance  TechCorp       972000.0
7  108    Helen   27     San Diego   58000  Marketing  TechCorp       783000.0
8  109      Ivy   33        Dallas   69000         IT  TechCorp       931500.0
9  110     Jack   31      San Jose   71000    Finance  TechCorp       958500.0

In [ ]:
# 新增「高薪」欄位（若薪資高於 65000 則標記為 Yes，否則為 No）
def high_salary(salary):
    if salary > 65000:
        return 'Yes'
    else:
        return 'No'

df['High Salary2'] = df['Salary'].apply(high_salary)
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary,High Salary,High Salary2
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0,No,No
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0,No,No
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0,Yes,Yes
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0,Yes,Yes
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0,No,No
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0,No,No
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0,Yes,Yes
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0,No,No
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0,Yes,Yes
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0,Yes,Yes

In [ ]:
# 刪除「City」與「Department」欄位
df.drop(columns=['High Salary2'], inplace=True)
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary,High Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0,No
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0,No
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0,Yes
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0,Yes
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0,No
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0,No
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0,Yes
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0,No
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0,Yes
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0,Yes

In [ ]:
df = df.drop(columns=['High Salary'])
df

    ID     Name  Age          City  Salary Department   Company  Annual Salary
0  101    Alice   25      New York   50000         IT  TechCorp       675000.0
1  102      Bob   30   Los Angeles   60000         HR  TechCorp       810000.0
2  103  Charlie   35       Chicago   75000    Finance  TechCorp      1012500.0
3  104    David   40       Houston   80000  Marketing  TechCorp      1080000.0
4  105      Eve   22       Phoenix   45000         IT  TechCorp       607500.0
5  106    Frank   29  Philadelphia   62000         HR  TechCorp       837000.0
6  107    Grace   38   San Antonio   72000    Finance  TechCorp       972000.0
7  108    Helen   27     San Diego   58000  Marketing  TechCorp       783000.0
8  109      Ivy   33        Dallas   69000         IT  TechCorp       931500.0
9  110     Jack   31      San Jose   71000    Finance  TechCorp       958500.0

In [ ]:
# 使用串列方式新增一筆資料（按照 DataFrame 欄位順序）
df.loc[len(df)] = [111, 'Kevin', 28, 'Austin', 67000, 'IT', 'TechCorp', 360000]
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0
10,111,Kevin,28,Austin,67000,IT,TechCorp,360000.0

In [ ]:
new_data = [
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'}
]
new_df = pd.DataFrame(new_data)
new_df

    ID  Name  Age     City  Salary Department
0  112  Lily   26  Seattle   55000  Marketing

In [ ]:
df = pd.concat(  [df, new_df] ,ignore_index=True  )
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0
10,111,Kevin,28,Austin,67000,IT,TechCorp,360000.0
11,112,Lily,26,Seattle,55000,Marketing,NaN,NaN

In [ ]:
# 刪除索引為 2 的資料
df.drop(index=2, inplace=True)
df

     ID   Name  Age          City  Salary Department   Company  Annual Salary
0   101  Alice   25      New York   50000         IT  TechCorp       675000.0
1   102    Bob   30   Los Angeles   60000         HR  TechCorp       810000.0
3   104  David   40       Houston   80000  Marketing  TechCorp      1080000.0
4   105    Eve   22       Phoenix   45000         IT  TechCorp       607500.0
5   106  Frank   29  Philadelphia   62000         HR  TechCorp       837000.0
6   107  Grace   38   San Antonio   72000    Finance  TechCorp       972000.0
7   108  Helen   27     San Diego   58000  Marketing  TechCorp       783000.0
8   109    Ivy   33        Dallas   69000         IT  TechCorp       931500.0
9   110   Jack   31      San Jose   71000    Finance  TechCorp       958500.0
10  111  Kevin   28        Austin   67000         IT  TechCorp       360000.0
11  112   Lily   26       Seattle   55000  Marketing       NaN            NaN

In [ ]:
condition = df['Salary'] < 75000
df = df[condition]
df

     ID   Name  Age          City  Salary Department   Company  Annual Salary
0   101  Alice   25      New York   50000         IT  TechCorp       675000.0
1   102    Bob   30   Los Angeles   60000         HR  TechCorp       810000.0
4   105    Eve   22       Phoenix   45000         IT  TechCorp       607500.0
5   106  Frank   29  Philadelphia   62000         HR  TechCorp       837000.0
6   107  Grace   38   San Antonio   72000    Finance  TechCorp       972000.0
7   108  Helen   27     San Diego   58000  Marketing  TechCorp       783000.0
8   109    Ivy   33        Dallas   69000         IT  TechCorp       931500.0
9   110   Jack   31      San Jose   71000    Finance  TechCorp       958500.0
10  111  Kevin   28        Austin   67000         IT  TechCorp       360000.0
11  112   Lily   26       Seattle   55000  Marketing       NaN            NaN

In [ ]:
# 計算每一欄有多少個 NaN
df.isnull().sum()

ID               0
Name             0
Age              0
City             0
Salary           0
Department       0
Company          1
Annual Salary    1
dtype: int64

In [ ]:
df.isnull()

       ID   Name    Age   City  Salary  Department  Company  Annual Salary
0   False  False  False  False   False       False    False          False
1   False  False  False  False   False       False    False          False
4   False  False  False  False   False       False    False          False
5   False  False  False  False   False       False    False          False
6   False  False  False  False   False       False    False          False
7   False  False  False  False   False       False    False          False
8   False  False  False  False   False       False    False          False
9   False  False  False  False   False       False    False          False
10  False  False  False  False   False       False    False          False
11  False  False  False  False   False       False     True           True

In [24]:
df[   df.isnull().any(axis=1)   ]

     ID  Name  Age     City  Salary Department Company  Annual Salary
11  112  Lily   26  Seattle   55000  Marketing     NaN            NaN

In [25]:
df.isnull().any(axis=0)

ID               False
Name             False
Age              False
City             False
Salary           False
Department       False
Company           True
Annual Salary     True
dtype: bool

In [26]:
df.columns[  df.isnull().any(axis=0) ]

Index(['Company', 'Annual Salary'], dtype='object')

In [27]:
df.loc[4,'Salary'] = pd.NA
df

     ID   Name  Age          City   Salary Department   Company  Annual Salary
0   101  Alice   25      New York  50000.0         IT  TechCorp       675000.0
1   102    Bob   30   Los Angeles  60000.0         HR  TechCorp       810000.0
4   105    Eve   22       Phoenix      NaN         IT  TechCorp       607500.0
5   106  Frank   29  Philadelphia  62000.0         HR  TechCorp       837000.0
6   107  Grace   38   San Antonio  72000.0    Finance  TechCorp       972000.0
7   108  Helen   27     San Diego  58000.0  Marketing  TechCorp       783000.0
8   109    Ivy   33        Dallas  69000.0         IT  TechCorp       931500.0
9   110   Jack   31      San Jose  71000.0    Finance  TechCorp       958500.0
10  111  Kevin   28        Austin  67000.0         IT  TechCorp       360000.0
11  112   Lily   26       Seattle  55000.0  Marketing       NaN            NaN

In [28]:
# 用平均數填充 Salary 欄位
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

<ipython-input-28-29c5ab0df49b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

,ID,Name,Age,City,Salary,Department,Company,Annual Salary
0,101,Alice,25,New York,50000.000000,IT,TechCorp,675000.0
1,102,Bob,30,Los Angeles,60000.000000,HR,TechCorp,810000.0
4,105,Eve,22,Phoenix,62666.666667,IT,TechCorp,607500.0
5,106,Frank,29,Philadelphia,62000.000000,HR,TechCorp,837000.0
6,107,Grace,38,San Antonio,72000.000000,Finance,TechCorp,972000.0
7,108,Helen,27,San Diego,58000.000000,Marketing,TechCorp,783000.0
8,109,Ivy,33,Dallas,69000.000000,IT,TechCorp,931500.0
9,110,Jack,31,San Jose,71000.000000,Finance,TechCorp,958500.0
10,111,Kevin,28,Austin,67000.000000,IT,TechCorp,360000.0
11,112,Lily,26,Seattle,55000.000000,Marketing,NaN,NaN

In [29]:
df = df.dropna(axis=1)
df

     ID   Name  Age          City        Salary Department
0   101  Alice   25      New York  50000.000000         IT
1   102    Bob   30   Los Angeles  60000.000000         HR
4   105    Eve   22       Phoenix  62666.666667         IT
5   106  Frank   29  Philadelphia  62000.000000         HR
6   107  Grace   38   San Antonio  72000.000000    Finance
7   108  Helen   27     San Diego  58000.000000  Marketing
8   109    Ivy   33        Dallas  69000.000000         IT
9   110   Jack   31      San Jose  71000.000000    Finance
10  111  Kevin   28        Austin  67000.000000         IT
11  112   Lily   26       Seattle  55000.000000  Marketing